### ISSUE TITLE
Goals of this Project / Repo - Roadmap

### ISSUE THREAD

**Issue by deckerweb** [wp-repository/translation-toolkit#1]
### History

The original ["Codestyling Localization" plugin](http://wordpress.org/plugins/codestyling-localization/) was released years ago on WordPress.org and maintained over the years. For a lot of users it's a favorite plugin, including some popular plugin and theme shops recommending it.

However, in the last 2 years or so there were some development decisions by the original author that did not please everyone in the user base of the plugin.

Therefore, and because the plugin is fully GPL, we set up this Github.com repository to try to add some tweaks to the plugin and maybe forking it at some point. That's to discuss.

Any dev, who's already using this plugin or interested in doing so is welcome here to join in and give back some love this great i18n plugin for WordPress.
### New Goals / Planned Tweaks
- [ ] Remove the "feature" that includes all strings from a parent theme into its child themes
- [ ] Remove the "error"/ "warning" message if a plugin also (or only) uses the function load_textdomain() - instead of load_plugin_textdomain() or load_theme_textdomain()
- [ ] Implement better inline documentation - or add some doc blocks at all
- [ ] performance improvements
- [x] remove "Scripting Guard"
- [ ] re-evalutate "special cases" like WooCommerce
- [ ] integrate "all" features of WP i18n tools
- [ ] make use of core styling
- [ ] Any other feature or tweak? -- [Post some _Issue_ here!](https://github.com/wp-repository/codestyling-localization/issues)
